######################################################################
# Automatically generated by qmake (3.0) Tue Mar 24 18:39:44 2015
######################################################################

TEMPLATE = app
TARGET = litter
INCLUDEPATH += .

QT += gui widgets

SOURCES += \
    main.cpp \
    Litter.cpp \
    LitEditor.cpp \

HEADERS += \
    Litter.h \
    LitEditor.h \

FORMS += \
    Litter.ui \
    LitEditor.ui \
